name = "tty_example"
description = ""
version = "1.0.0"

authors = ["Heziode"]
maintainers = ["Quentin DAUPRAT (Heziode) <contact@adarium.dev>"]
maintainers-logins = ["heziode"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
termicap = "*"

[[pins]]
termicap = { path = "../.." }