name = "terminal_id_demo"
description = ""
version = "0.1.0-dev"

authors = ["Heziode"]
maintainers = ["Heziode <heziode@protonmail.com>"]
maintainers-logins = ["heziode"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
termicap = "*"

[[pins]]
termicap = { path = "../.." }
