name = "termicap"
description = ""
version = "0.1.0-dev"

authors = ["Heziode"]
maintainers = ["Heziode <heziode@protonmail.com>"]
maintainers-logins = ["heziode"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
sparklib = "^15.1.0"

[depends-on.'case(os)'.windows]
win32ada = "^26.0.0"

[build-switches]

# On non-Windows, point gprbuild at the local stub
[build-switches.'case(os)'.windows]


[environment.'case(os)'.'...']
GPR_PROJECT_PATH.prepend = "${CRATE_ROOT}/gpr"
