name = "wcwidth_demo"
description = "Usage example for Termicap.Wcwidth (wcwidth() probing for Unicode level)"
version = "1.0.0"

authors = ["Heziode"]
maintainers = ["Heziode <heziode@protonmail.com>"]
maintainers-logins = ["heziode"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["wcwidth_demo"]

[[depends-on]]
termicap = "*"

[[pins]]
termicap = { path = "../.." }
