name = "cell_width_demo"
description = "Usage example for Termicap.Cell_Width (cell width measurement tables)"
version = "0.1.0-dev"

authors = ["Heziode"]
maintainers = ["Heziode <heziode@protonmail.com>"]
maintainers-logins = ["heziode"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["cell_width_demo"]

[[depends-on]]
termicap = "*"

[[pins]]
termicap = { path = "../.." }
