name = "dimensions_demo"
description = ""
version = "1.0.0"

authors = ["Your Name"]
maintainers = ["Your Name <heziode@protonmail.com>"]
maintainers-logins = ["Heziode"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["dimensions_demo"]

[[depends-on]]
termicap = "*"

[[pins]]
termicap = { path = "../.." }
