name = "override_demo"
description = "Usage examples for Termicap.Override - global enable/disable override"
version = "1.0.0"

authors = ["Heziode"]
maintainers = ["Heziode <heziode@protonmail.com>"]
maintainers-logins = ["heziode"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
termicap = "*"

[[pins]]
termicap = { path = "../.." }
