name = "termicap_examples"
description = ""
version = "1.0.0"

authors = ["Heziode"]
maintainers = ["Heziode <heziode@protonmail.com>"]
maintainers-logins = ["heziode"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
termicap = "*"

[[pins]]
termicap = { path = ".." }