name = "da1_demo"
description = ""
version = "0.1.0-dev"

authors = ["Your Name"]
maintainers = ["Your Name <heziode@protonmail.com>"]
maintainers-logins = ["Heziode"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["da1_demo"]

[[depends-on]]
termicap = "*"

[[pins]]
termicap = { path = "../.." }
